name: 'Docker Login'
description: 'Log in to DockerHub'
inputs:
  username:
    description: 'DockerHub username'
    required: true
  password:
    description: 'DockerHub password'
    required: true
runs:
  using: 'docker'
  image: 'docker:latest'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    echo "${{ inputs.password }}" | docker login -u "${{ inputs.username }}" --password-stdin
