name: Docker Login
description: Log in to DockerHub
runs:
  using: "composite" # Esto indica que es una acción compuesta, lo que permite combinar múltiples comandos en un solo archivo.
  steps:
  - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    shell: bash
