name: CD Workflow for Production

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Workflow for Production"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        uses: ./.github/actions/docker-login

      - name: Pull Docker Image from Production
        run: docker pull miriamblanco/my-angular-app:${{ github.sha }}-production

      - name: Run Docker Container in Production
        run: |
          docker stop my-angular-app || true
          docker rm my-angular-app || true
          docker run -d -p 8080:8080 --name my-angular-app miriamblanco/my-angular-app:${{ github.sha }}-production
          sleep 30  # Espera a que el contenedor se inicie

      - name: Check Production Deployment
        run: curl http://localhost
