name: CI Workflow for uat

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - development
  # pull_request:
  #   branches:
  #     - development

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    with:
      node_version: '20'
      environment: 'uat'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

