name: Reusable Build Workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: npm run build --prod

      - name: Build Docker Image
        run: |
          docker build -t miriamblanco/my-angular-app:${{ github.sha }}-${{ inputs.environment }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push miriamblanco/my-angular-app:${{ github.sha }}-${{ inputs.environment }}
        # Construye la imagen Docker con una etiqueta que depende del entorno (uat o prod)
